import { IAppData } from "../AppData/appdata.types";

export type AppDataState = {
  appData: IAppData;
};

enum AppDataActionType {
  RESET_SHOW_PRODUCT_LIST = "RESET_SHOW_PRODUCT_LIST",
  DELETE_FEEDBACK = "DELETE_FEEDBACK",
  INVALID_INPUT = "INVALID_INPUT",
  SET_COMMENT = "SET_COMMENT",
  SET_REPLY = "SET_REPLY",
  TOGGLE_REPLY = "TOGGLE_REPLY",
  SET_ID_COMMENT_RECEIVING_REPLY = "SET_ID_COMMENT_RECEIVING_REPLY",
  ADD_COMMENT = "ADD_COMMENT",
  ADD_REPLY = "ADD_REPLY",
  ADD_FEEDBACK = "ADD_FEEDBACK",
  EDIT_FEEDBACK = "EDIT_FEEDBACK",
  INITIALIZE_INPUT = "INITIALIZE_INPUT",
  TOGGLE_CATEGORY_DROPDOWN = "TOGGLE_CATEGORY_DROPDOWN",
  TOGGLE_STATUS_DROPDOWN = "TOGGLE_STATUS_DROPDOWN",
  TOGGLE_SORT_DROPDOWN = "TOGGLE_SORT_DROPDOWN",
  SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY",
  SET_SELECTED_STATUS = "SET_SELECTED_STATUS",
  SET_SELECTED_SORT_OPTION = "SET_SELECTED_SORT_OPTION",
  SET_FEEDBACK_FORM_INPUT = "SET_FEEDBACK_FORM_INPUT",
  SET_DEFAULT_FORM_VALUES = "SET_DEFAULT_FORM_VALUES",
  SET_TAB_INDEX = "SET_ACTIVE_TAB_INDEX",
  TOGGLE_MOBILE_NAV = "TOGGLE_MOBILE_NAV",
  ACTIVATE_DRAG = "ACTIVATE_DRAG",
  SET_REQUEST_STATUS = "SET_REQUEST_STATUS",
  SET_REQUEST_INDEX = "SET_REQUEST_INDEX",
  FILTER_PRODUCT_REQUESTS = "FILTER_PRODUCT_REQUESTS",
  SET_UPVOTED_REQUESTS = "SET_UPVOTED_REQUESTS",
}

export interface AppDataAction {
  type: AppDataActionType;
  payload: any;
}

export type Dispatch = (action: AppDataAction) => any;
