import { IAppData } from "../AppData/appdata.types";

export type AppDataState = {
  appData: IAppData;
};

enum AppDataActionType {
  DELETE_FEEDBACK = "DELETE_FEEDBACK",
  INVALID_INPUT = "INVALID_INPUT",
  SET_COMMENT = "SET_COMMENT",
  SET_REPLY = "SET_REPLY",
  TOGGLE_REPLY = "TOGGLE_REPLY",
  SET_ID_COMMENT_RECEIVING_REPLY = "SET_ID_COMMENT_RECEIVING_REPLY",
  ADD_COMMENT = "ADD_COMMENT",
  ADD_REPLY = "ADD_REPLY",
  ADD_FEEDBACK = "ADD_FEEDBACK",
  INITIALIZE_INPUT = "INITIALIZE_INPUT",
  TOGGLE_CATEGORY_DROPDOWN = "TOGGLE_CATEGORY_DROPDOWN",
  TOGGLE_STATUS_DROPDOWN = "TOGGLE_STATUS_DROPDOWN",
  SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY",
  SET_SELECTED_STATUS = "SET_SELECTED_STATUS",
  SET_FEEDBACK_FORM_INPUT = "SET_FEEDBACK_FORM_INPUT",
  SET_DEFAULT_FORM_VALUES = "SET_DEFAULT_FORM_VALUES",
}

export interface AppDataAction {
  type: AppDataActionType;
  payload: any;
}

export type Dispatch = (action: AppDataAction) => any;
